local I = require('openmw.interfaces')

I.Settings.registerPage {
    key = 'MeritsOfService',
    l10n = 'MeritsOfService',
    name = 'page_name',
    description = 'page_description',
}

I.Settings.registerGroup {
    key = 'SettingsMeritsOfService_rewards',
    page = 'MeritsOfService',
    l10n = 'MeritsOfService',
    name = 'rewards_groupName',
    description = 'rewards_groupDesc',
    permanentStorage = true,
    order = 1,
    settings = {
        {
            key = 'questsPerReward',
            name = 'questsPerReward_name',
            renderer = 'number',
            integer = true,
            default = 3,
            min = 1,
        },
        {
            key = 'minSkillReward',
            name = 'minSkillReward_name',
            renderer = 'number',
            integer = true,
            default = 3,
            min = 0,
        },
        {
            key = 'maxSkillReward',
            name = 'maxSkillReward_name',
            renderer = 'number',
            integer = true,
            default = 5,
            min = 0,
        },
        {
            key = 'minAttributeReward',
            name = 'minAttributeReward_name',
            renderer = 'number',
            integer = true,
            default = 2,
            min = 0,
        },
        {
            key = 'maxAttributeReward',
            name = 'maxAttributeReward_name',
            renderer = 'number',
            integer = true,
            default = 3,
            min = 0,
        },
        {
            key = 'skillRewardWeight',
            name = 'skillRewardWeight_name',
            renderer = 'number',
            integer = false,
            default = 1,
            min = 0,
        },
        {
            key = 'attributeRewardWeight',
            name = 'attributeRewardWeight_name',
            renderer = 'number',
            integer = false,
            default = 1,
            min = 0,
        },
        {
            key = 'carrySkillXp',
            name = 'carrySkillXp_name',
            renderer = 'checkbox',
            default = true,
        },
        {
            key = 'capSkills',
            name = 'capSkills_name',
            description = 'capSkills_description',
            renderer = 'number',
            integer = true,
            default = 100,
            min = 1,
        },
        {
            key = 'capAttr',
            name = 'capAttr_name',
            description = 'capAttr_description',
            renderer = 'number',
            integer = true,
            default = 100,
            min = 1,
        },
        {
            key = 'triggerSkillupHandlers',
            name = 'triggerSkillupHandlers_name',
            description = 'triggerSkillupHandlers_description',
            renderer = 'checkbox',
            default = true,
        },
        {
            key = 'luckRewardChance',
            name = 'luckRewardChance_name',
            description = 'luckRewardChance_description',
            renderer = 'number',
            integer = false,
            default = 0.1,
            min = 0,
            max = 1,
        },
    }
}
