local I = require('openmw.interfaces')

I.Settings.registerPage {
    key = 'MeritsOfService',
    l10n = 'MeritsOfService_settings',
    name = 'page_name',
    description = 'page_description',
}

I.Settings.registerGroup {
    key = 'SettingsMeritsOfService_rewards',
    page = 'MeritsOfService',
    l10n = 'MeritsOfService',
    name = 'rewards_groupName',
    description = 'rewards_groupDescription',
    permanentStorage = true,
    order = 1,
    settings = {
        {
            key = 'questsPerReward',
            name = 'questsPerReward_name',
            description = 'questsPerReward_description',
            renderer = 'number',
            integer = true,
            default = 3,
            min = 1,
        },
        {
            key = 'minSkillReward',
            name = 'minSkillReward_name',
            description = 'minSkillReward_description',
            renderer = 'number',
            integer = true,
            default = 3,
            min = 0,
        },
        {
            key = 'maxSkillReward',
            name = 'maxSkillReward_name',
            description = 'maxSkillReward_description',
            renderer = 'number',
            integer = true,
            default = 5,
            min = 0,
        },
        {
            key = 'minAttributeReward',
            name = 'minAttributeReward_name',
            description = 'minAttributeReward_description',
            renderer = 'number',
            integer = true,
            default = 2,
            min = 0,
        },
        {
            key = 'maxAttributeReward',
            name = 'maxAttributeReward_name',
            description = 'maxAttributeReward_description',
            renderer = 'number',
            integer = true,
            default = 3,
            min = 0,
        },
        {
            key = 'skillRewardWeight',
            name = 'skillRewardWeight_name',
            description = 'skillRewardWeight_description',
            renderer = 'number',
            integer = false,
            default = 1,
            min = 0,
        },
        {
            key = 'attributeRewardWeight',
            name = 'attributeRewardWeight_name',
            description = 'attributeRewardWeight_description',
            renderer = 'number',
            integer = false,
            default = 1,
            min = 0,
        },
        {
            key = 'skillsContributeToLevel',
            name = 'skillsContributeToLevel_name',
            description = 'skillsContributeToLevel_description',
            renderer = 'checkbox',
            default = false,
        },
        {
            key = 'carrySkillXp',
            name = 'carrySkillXp_name',
            description = 'carrySkillXp_description',
            renderer = 'checkbox',
            default = true,
        },
    }
}
